language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
matrix:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/rails60.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails60.gemfile
before_script:
  - cd spec/dummy
  - bundle exec rake dbs:migrate RAILS_ENV=test
  - cd ../..
script:
  - bundle exec rspec
