default: &default
  adapter: mysql2
  pool: 100
  timeout: 1000
  checkout_timeout: 1
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

ci: &ci
  host: 127.0.0.1
  username: root

development:
  primary:
    <<: *default
    database: djm_development
  secondary:
    <<: *default
    database: djm_development2
  primary_replica:
    <<: *default
    database: djm_development
    replica: true
  secondary_replica:
    <<: *default
    database: djm_development2
    replica: true

test:
  primary:
    <<: *default
    <<: *ci
    database: djm_test
  secondary:
    <<: *default
    <<: *ci
    database: djm_test2
  primary_replica:
    <<: *default
    <<: *ci
    database: djm_test
    replica: true
  secondary_replica:
    <<: *default
    <<: *ci
    database: djm_test2
    replica: true

production:
  primary:
    <<: *default
    database: djm_production
  secondary:
    <<: *default
    database: djm_production2
  primary_replica:
    <<: *default
    database: djm_production
    replica: true
  secondary_replica:
    <<: *default
    database: djm_production2
    replica: true
