default: &default
  adapter: postgresql
  pool: 100
  timeout: 1000
  checkout_timeout: 1

ci: &ci
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  primary:
    <<: *default
    database: djm_development
  secondary:
    <<: *default
    database: djm_development2
  primary_replica:
    <<: *default
    database: djm_development
    replica: true
  secondary_replica:
    <<: *default
    database: djm_development2
    replica: true

test:
  primary:
    <<: *default
    <<: *ci
    database: djm_test
  secondary:
    <<: *default
    <<: *ci
    database: djm_test2
  primary_replica:
    <<: *default
    <<: *ci
    database: djm_test
    replica: true
  secondary_replica:
    <<: *default
    <<: *ci
    database: djm_test2
    replica: true

production:
  primary:
    <<: *default
    database: djm_production
  secondary:
    <<: *default
    database: djm_production2
  primary_replica:
    <<: *default
    database: djm_production
    replica: true
  secondary_replica:
    <<: *default
    database: djm_production2
    replica: true
