default: &default
  adapter: postgresql
  pool: 100
  timeout: 1000
  checkout_timeout: 1

development:
  primary:
    <<: *default
    database: djm_development

test:
  primary:
    <<: *default
    database: djm_test

production:
  primary:
    <<: *default
    database: djm_production
