default: &default
  adapter: postgresql
  pool: 100
  timeout: 1000
  checkout_timeout: 1

development:
  primary:
    <<: *default
    database: djm_development
  secondary:
    <<: *default
    database: djm_development2

test:
  primary:
    <<: *default
    database: djm_test
  secondary:
    <<: *default
    database: djm_test2

production:
  primary:
    <<: *default
    database: djm_production
  secondary:
    <<: *default
    database: djm_production2
