default: &default
  adapter: sqlite3
  pool: 100
  timeout: 1000
  idle_timeout: 1000
  checkout_timeout: 1

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  secondary:
    <<: *default
    database: db/development2.sqlite3
  primary_replica:
    <<: *default
    database: db/development.sqlite3
    replica: true
  secondary_replica:
    <<: *default
    database: db/development2.sqlite3
    replica: true

test:
  primary:
    <<: *default
    database: db/test.sqlite3
  secondary:
    <<: *default
    database: db/test2.sqlite3
  primary_replica:
    <<: *default
    database: db/test.sqlite3
    replica: true
  secondary_replica:
    <<: *default
    database: db/test2.sqlite3
    replica: true

production:
  primary:
    <<: *default
    database: db/production.sqlite3
  secondary:
    <<: *default
    database: db/production2.sqlite3
  primary_replica:
    <<: *default
    database: db/production.sqlite3
    replica: true
  secondary_replica:
    <<: *default
    database: db/production2.sqlite3
    replica: true
