name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2]
        gemfile: ['rails60', 'rails61', 'rails70']
        database: ['single', 'multiple']

    name: ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}

    env:
      DATABASE_CONFIG: ${{ matrix.gemfile }}
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Prepare test
      run: |
        cd spec/dummy
        BUNDLE_GEMFILE=../../${{ env.BUNDLE_GEMFILE }} RAILS_ENV=test bundle exec rake db:migrate
        cd ../..
    - name: Run test
      run: |
        bundle exec rspec
